# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Liam Scott | Front-End Developer
email: liam@liamscott.me
description: > # this means to ignore newlines until "baseurl:"
  Liam Scott is a talented young web developer based in NYC. Among
  his favorite things are a good cup of tea, massages, and of course
  kittens.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://liamscott.me" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  liamscott

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/_sass
  style: compressed